import Foundation

/// A reviewed, offline glossary entry. Definitions are authored and reviewed in
/// the app, never generated by the model at runtime. The model may only choose
/// which `id` to reference.
struct CoachGlossaryTerm: Codable, Equatable, Identifiable {
    let id: String
    let canonicalLabel: String
    let aliases: [String]
    let category: Category
    let localizedContent: [String: LocalizedContent]
    let learnMoreURL: String?
    let version: Int

    enum Category: String, Codable {
        case trainingLoad = "training_load"
        case recovery
        case heartRate = "heart_rate"
        case pace
        case workoutType = "workout_type"
        case performance
    }

    struct LocalizedContent: Codable, Equatable {
        let title: String
        var fullName: String?
        let simpleExplanation: String
        var whyItMatters: String?
        var interpretation: String?
        var caution: String?
    }

    /// Localized content for the selected language, falling back to English so a
    /// language without a reviewed translation never shows an empty sheet.
    func content(for language: CoachLanguage) -> LocalizedContent {
        localizedContent[language.rawValue]
            ?? localizedContent[CoachLanguage.en.rawValue]
            ?? localizedContent.values.first!
    }
}

/// A resolved reference the renderer hands to the glossary sheet. `currentValue`
/// is only ever populated from a validated structured metric, never parsed from
/// prose.
struct CoachGlossaryReference: Equatable {
    let termId: String
    let displayLabel: String
    var currentValue: String?
    var interpretation: String?
}

/// One inline piece of a Coach message after glossary parsing. Computed at
/// render time from the stored string, so streaming and localization can change
/// offsets without breaking anything.
enum CoachGlossarySegment: Equatable {
    case text(String)
    case term(id: String, label: String)
}

enum CoachGlossary {
    static let version = 1

    static func term(id: String) -> CoachGlossaryTerm? {
        byID[id.lowercased()]
    }

    /// Resolves a canonical label or alias (case-insensitive) to its term.
    static func term(matchingAlias alias: String) -> CoachGlossaryTerm? {
        byAlias[alias.lowercased()]
    }

    /// Rewrites known model-output typos in NEW assistant text before it is
    /// persisted. Word-boundary matched. Never call on user-authored text.
    static func normalizeModelText(_ text: String) -> String {
        var result = text
        for pair in typoCorrections {
            result = replaceWholeWord(pair.wrong, with: pair.right, in: result)
        }
        return result
    }

    // MARK: - Internals

    private static let typoCorrections: [(wrong: String, right: String)] = [
        ("AWCR", "ACWR")
    ]

    private static func replaceWholeWord(_ needle: String, with replacement: String, in text: String) -> String {
        guard !text.isEmpty,
              let regex = try? NSRegularExpression(
                pattern: "(?<![A-Za-z0-9_])\(NSRegularExpression.escapedPattern(for: needle))(?![A-Za-z0-9_])",
                options: [.caseInsensitive]
              )
        else { return text }
        let range = NSRange(text.startIndex..<text.endIndex, in: text)
        return regex.stringByReplacingMatches(in: text, range: range, withTemplate: replacement)
    }

    private static let byID: [String: CoachGlossaryTerm] = {
        Dictionary(uniqueKeysWithValues: terms.map { ($0.id.lowercased(), $0) })
    }()

    private static let byAlias: [String: CoachGlossaryTerm] = {
        var map: [String: CoachGlossaryTerm] = [:]
        for term in terms {
            map[term.canonicalLabel.lowercased()] = term
            for alias in term.aliases {
                map[alias.lowercased()] = term
            }
        }
        return map
    }()

    static let terms: [CoachGlossaryTerm] = [
        CoachGlossaryTerm(
            id: "acwr",
            canonicalLabel: "ACWR",
            aliases: [],
            category: .trainingLoad,
            localizedContent: [
                "vi": .init(
                    title: "Tỷ lệ tải cấp tính/mạn tính",
                    fullName: "Acute:Chronic Workload Ratio",
                    simpleExplanation: "So sánh tải tập gần đây với mức tải mà cơ thể đã quen trong một khoảng thời gian dài hơn.",
                    whyItMatters: "Giúp nhận biết tải tập có đang tăng quá nhanh so với nền tảng gần đây hay không.",
                    interpretation: nil,
                    caution: "Không dùng ACWR một mình để kết luận rằng một mức tải là an toàn hoặc dự đoán chấn thương."
                ),
                "en": .init(
                    title: "Acute:Chronic Workload Ratio",
                    fullName: "Acute:Chronic Workload Ratio",
                    simpleExplanation: "Compares your recent training load with the load your body is used to over a longer period.",
                    whyItMatters: "Helps flag whether training load is rising quickly relative to your recent baseline.",
                    interpretation: nil,
                    caution: "Don't use ACWR alone to decide a load is safe or to predict injury."
                )
            ],
            learnMoreURL: nil,
            version: 1
        ),
        CoachGlossaryTerm(
            id: "hrv",
            canonicalLabel: "HRV",
            aliases: [],
            category: .recovery,
            localizedContent: [
                "vi": .init(
                    title: "Biến thiên nhịp tim",
                    fullName: "Heart Rate Variability",
                    simpleExplanation: "HRV là mức thay đổi về thời gian giữa các nhịp tim liên tiếp.",
                    whyItMatters: "Xu hướng HRV có thể giúp nhận biết cơ thể đang hồi phục tốt hay đang chịu thêm stress.",
                    interpretation: nil,
                    caution: "Nên so sánh HRV với mức bình thường của chính bạn, không so trực tiếp với người khác. Một ngày thấp hoặc cao không đủ để đưa ra kết luận."
                ),
                "en": .init(
                    title: "Heart Rate Variability",
                    fullName: "Heart Rate Variability",
                    simpleExplanation: "HRV is the variation in time between consecutive heartbeats.",
                    whyItMatters: "HRV trends can hint whether your body is recovering well or under added stress.",
                    interpretation: nil,
                    caution: "Compare HRV to your own normal, not to other people. One high or low day isn't enough to conclude anything."
                )
            ],
            learnMoreURL: nil,
            version: 1
        ),
        CoachGlossaryTerm(
            id: "rhr",
            canonicalLabel: "RHR",
            aliases: [],
            category: .heartRate,
            localizedContent: [
                "vi": .init(
                    title: "Nhịp tim nghỉ",
                    fullName: "Resting Heart Rate",
                    simpleExplanation: "Số lần tim đập trong một phút khi cơ thể đang nghỉ ngơi, thường được đo vào lúc ngủ hoặc ngay sau khi thức dậy.",
                    whyItMatters: "Nếu RHR cao hơn mức bình thường của bạn trong nhiều ngày, cơ thể có thể đang mệt, chịu stress hoặc chưa hồi phục hoàn toàn.",
                    interpretation: nil,
                    caution: "Coach phải xem xu hướng nhiều ngày và kết hợp với các tín hiệu khác, không kết luận chỉ từ một lần đo."
                ),
                "en": .init(
                    title: "Resting Heart Rate",
                    fullName: "Resting Heart Rate",
                    simpleExplanation: "The number of times your heart beats per minute at rest, usually measured during sleep or right after waking.",
                    whyItMatters: "If your RHR stays above your normal for several days, your body may be tired, stressed, or not fully recovered.",
                    interpretation: nil,
                    caution: "Coach looks at multi-day trends combined with other signals, never a single reading."
                )
            ],
            learnMoreURL: nil,
            version: 1
        ),
        CoachGlossaryTerm(
            id: "t_pace",
            canonicalLabel: "T pace",
            aliases: ["T-pace", "Threshold pace"],
            category: .pace,
            localizedContent: [
                "vi": .init(
                    title: "Pace ngưỡng",
                    fullName: nil,
                    simpleExplanation: "Mức pace nhanh nhưng vẫn có thể duy trì có kiểm soát trong một buổi tập ngưỡng.",
                    whyItMatters: "Giúp cải thiện khả năng duy trì tốc độ cao trong thời gian dài.",
                    interpretation: nil,
                    caution: "Pace ngưỡng phải được cá nhân hóa theo năng lực hiện tại, không nên lấy trực tiếp từ mục tiêu cuộc đua."
                ),
                "en": .init(
                    title: "Threshold pace",
                    fullName: nil,
                    simpleExplanation: "A fast but controlled pace you can sustain through a threshold session.",
                    whyItMatters: "Improves your ability to hold a strong pace for longer.",
                    interpretation: nil,
                    caution: "Threshold pace must be personalized to your current fitness, not taken straight from a race goal."
                )
            ],
            learnMoreURL: nil,
            version: 1
        ),
        CoachGlossaryTerm(
            id: "e_pace",
            canonicalLabel: "E pace",
            aliases: ["E-pace", "Easy pace"],
            category: .pace,
            localizedContent: [
                "vi": .init(
                    title: "Pace chạy nhẹ",
                    fullName: nil,
                    simpleExplanation: "Mức pace thoải mái, có thể nói chuyện bằng các câu tương đối đầy đủ trong lúc chạy.",
                    whyItMatters: "Dùng để tích lũy quãng đường và hỗ trợ hồi phục mà không tạo quá nhiều mệt mỏi.",
                    interpretation: nil,
                    caution: "Không ép pace chạy nhẹ vào một con số cố định khi thời tiết, địa hình hoặc mức hồi phục thay đổi."
                ),
                "en": .init(
                    title: "Easy pace",
                    fullName: nil,
                    simpleExplanation: "A comfortable pace where you can talk in fairly full sentences while running.",
                    whyItMatters: "Builds mileage and supports recovery without adding too much fatigue.",
                    interpretation: nil,
                    caution: "Don't force easy pace to a fixed number when weather, terrain, or recovery change."
                )
            ],
            learnMoreURL: nil,
            version: 1
        )
    ]
}
